seed: 1
record_video: no

environment:
  render: True
# just testing commenting
  num_envs: 200
  eval_every_n: 10
  num_threads: 30
  #simulation_dt: 0.0025
  simulation_dt: 0.01
  control_dt: 0.01
  max_time: 2.0
  reward:
    ForwardVel:
      coeff: 0.1
    GenTorque:
      coeff: -2e-4
    GenVelocity:
      coeff: -1e-4
    ForwardPos:
      coeff: 0.3
    YaxisPos:
      coeff: -1
    GeneralHipsAngles:
      coeff: -1e-1
    GeneralBodyOrientation:
      coeff: -6e-2
    ClearAndSlip:
      coeff: -1e-1
    BodyHeight:
      coeff: 5e-2
    rewardSmoothTorqVel:
      coeff: -2e-4

architecture:
  policy_net: [256, 256]
  value_net: [256, 256]
