seed: 1
record_video: no

environment:
  render: True
# just testing commenting
  num_envs: 500
  eval_every_n: 500
  num_threads: 30
  simulation_dt: 0.0025
  #simulation_dt: 0.01
  control_dt: 0.01
  max_time: 2.0
  reward:
    GenTorque:
      coeff: -1e-6
    GenVelocity:
      coeff: -5e-6
    axisPos:
      coeff: -5e-3
    GeneralHipsAngles:
      coeff: -1e-3
    GeneralBodyOrientation:
      coeff: -1e-3
    BodyHeight:
      coeff: 5e-2
    rewardSmoothTorqVel:
      coeff: -1e-6
    fullContact:
      coeff: 1e-2
    difference:
      coeff: -1e-3

architecture:
  policy_net: [128, 128]
  value_net: [128, 128]
